-- Practice Questions
-- Exercises
-- 1.	Create a list of employee names and their full addresses using the INNER JOIN.
SELECT E.FIRSTNAME, E.LASTNAME, AD.ADDRESSLINE1, AD.ADDRESSLINE2, AD.CITY, AD.STATE, AD.ZIP1, AD.ZIP2 
FROM EMPLOYEES E
INNER JOIN ADDRESSES AD
ON E.EMPLOYEEID = AD.EMPLOYEEID

-- 2.	Create a list of employee names and their full addresses using the INNER JOIN for employees who live either in Massachusetts or California.
SELECT E.FIRSTNAME, E.LASTNAME, AD.ADDRESSLINE1, AD.ADDRESSLINE2, AD.CITY, AD.STATE, AD.ZIP1, AD.ZIP2 
FROM EMPLOYEES E
INNER JOIN ADDRESSES AD
ON E.EMPLOYEEID = AD.EMPLOYEEID
WHERE AD.STATE = 'CA' OR AD.STATE = 'MA'

-- 3.	Create an example of a Cartesian product using the Employees and Addresses table.
SELECT * FROM EMPLOYEES 
CROSS JOIN ADDRESSES

SELECT * 
FROM EMPLOYEES, ADDRESSES 

-- 4.	Use a LEFT OUTER JOIN to list all employee first and last names as well as the gender and birthdates of their dependents if they have any.
SELECT E.FIRSTNAME EMP_FNAME, E.LASTNAME EMP_LNAME, D.GENDER DEP_GENDER, D.BIRTHDATE DEP_BIRTHDATE 
FROM EMPLOYEES E
LEFT OUTER JOIN DEPENDENTS D
ON E.EMPLOYEEID = D.EMPLOYEEID

-- 5.	Use a RIGHT OUTER JOIN to list all employee first and last names as well as the gender and birthdates of their dependents if they have any (Same as above but change location of tables).
SELECT E.FIRSTNAME EMP_FNAME, E.LASTNAME EMP_LNAME, D.GENDER DEP_GENDER, D.BIRTHDATE DEP_BIRTHDATE 
FROM DEPENDENTS D
RIGHT OUTER JOIN EMPLOYEES E
ON E.EMPLOYEEID = D.EMPLOYEEID

-- 6.	Use a SELF JOIN to select the employee first name, last name, title as well as the manager's first name, last name and title.
SELECT E1.FIRSTNAME EMP_FIRSTNAME, E1.LASTNAME EMP_LASTNAME, E2.FIRSTNAME MAN_FIRSTNAME, E2.LASTNAME MAN_FIRSTNAME, E2.TITLE AS MANAGERTITLE
FROM EMPLOYEES E1 
INNER JOIN EMPLOYEES E2 
ON E2.EMPLOYEEID = E1.MANAGERID	

-- 7.	Retrieve the employee first name, last name, department name and group name for the employee named Gail Erickson.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, D.GROUPNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEESDEPARTMENTS ED
ON E.EMPLOYEEID = ED.EMPLOYEEID 
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = ED.DEPARTMENTID 
WHERE E.FIRSTNAME = 'Gail' AND E.LASTNAME = 'Erickson'

-- 8.	Retrieve the employee first name, last name, address, city, state, zip, department name and group name for the employee named David Bradley.
SELECT E.FIRSTNAME, E.LASTNAME, AD.ADDRESSLINE1, AD.ADDRESSLINE2, AD.CITY, AD.STATE, AD.ZIP1, AD.ZIP2, D.DEPARTMENTNAME, D.GROUPNAME
FROM EMPLOYEES E
INNER JOIN ADDRESSES AD
ON E.EMPLOYEEID = AD.EMPLOYEEID
INNER JOIN EMPLOYEESDEPARTMENTS ED
ON E.EMPLOYEEID = ED.EMPLOYEEID 
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = ED.DEPARTMENTID 
WHERE E.FIRSTNAME = 'David' AND E.LASTNAME = 'Bradley'

-- 9.	Retrieve the employee first name, last name, dependent first name, last name and gender for female dependents.
SELECT E.FIRSTNAME EMP_FNAME, E.LASTNAME EMP_LNAME, D.FIRSTNAME D_FNAME, D.LASTNAME D_LNAME, D.GENDER D_GENDER
FROM EMPLOYEES E
INNER JOIN DEPENDENTS D
ON E.EMPLOYEEID = D.EMPLOYEEID
WHERE D.GENDER = 'F' 

-- 10.	Retrieve the employee first name, last name, dependent first name, last name, birth date for dependents who have birth dates less than or equal to 11/02/2008. 
SELECT E.FIRSTNAME EMP_FNAME, E.LASTNAME EMP_LNAME, D.FIRSTNAME D_FNAME, D.LASTNAME D_LNAME, D.BIRTHDATE D_BIRTHDATE
FROM EMPLOYEES E
INNER JOIN DEPENDENTS D
ON E.EMPLOYEEID = D.EMPLOYEEID
WHERE D.BIRTHDATE::DATE <= '11/02/2008'

-- 11.	Use LEFT OUTER JOINS to list all Employees, their Department Names, and their dependent names, if any.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, DP.FIRSTNAME, DP.LASTNAME
FROM EMPLOYEES E 
LEFT OUTER JOIN EMPLOYEESDEPARTMENTS ED
ON E.EMPLOYEEID = ED.EMPLOYEEID 
LEFT OUTER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = ED.DEPARTMENTID 
LEFT OUTER JOIN DEPENDENTS DP
ON E.EMPLOYEEID = DP.EMPLOYEEID

-- 12.	Use RIGHT OUTER JOINS to list all Employees, their Department Names, and their dependent names, like you did in the question above.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME, DP.FIRSTNAME, DP.LASTNAME
FROM DEPENDENTS DP 
RIGHT OUTER JOIN EMPLOYEES E
ON E.EMPLOYEEID = DP.EMPLOYEEID
RIGHT OUTER JOIN EMPLOYEESDEPARTMENTS ED
ON E.EMPLOYEEID = ED.EMPLOYEEID 
RIGHT OUTER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = ED.DEPARTMENTID 

-- 13.	Retrieve the employee first name, last name, dependent first name, last name and gender for dependents who were born in or before 1998.
SELECT E.FIRSTNAME EMP_FNAME, E.LASTNAME EMP_LNAME, D.FIRSTNAME D_FNAME, D.LASTNAME D_LNAME, D.GENDER D_GENDER
FROM EMPLOYEES E
INNER JOIN DEPENDENTS D
ON E.EMPLOYEEID = D.EMPLOYEEID
WHERE D.BIRTHDATE::DATE <= '12/31/1998'

-- 14.	Retrieve all employees belonging to the department “Marketing” using INNER JOINS.
SELECT E.FIRSTNAME, E.LASTNAME, D.DEPARTMENTNAME
FROM EMPLOYEES E
INNER JOIN EMPLOYEESDEPARTMENTS ED
ON E.EMPLOYEEID = ED.EMPLOYEEID 
INNER JOIN DEPARTMENTS D
ON D.DEPARTMENTID = ED.DEPARTMENTID 
WHERE D.DEPARTMENTNAME = 'Marketing'

-- 15.	Retrieve the first name, last name, and title of the manager responsible for the Employee with the first name “Ben” and last name “Miller”.
SELECT E2.FIRSTNAME, E2.LASTNAME, E2.TITLE 
FROM EMPLOYEES E1 
INNER JOIN EMPLOYEES E2 
ON E2.EMPLOYEEID = E1.MANAGERID	
WHERE E1.FIRSTNAME = 'Ben' AND E1.LASTNAME = 'Miller'